# Use root/mysql as user/password credentials

version: '3.8'

services:

    db:
        image: sat-smysql
        command:
            --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: miBase
        ports:
            - "33306:3306"